"""The implementation decisions, ambiguities and findings on the rule text, as one
source for measure.md and evidence2.json."""

DECISIONS = [
    {"id": "D1", "rule": "R1",
     "question": "Which tag is 'the previous tag'?",
     "decision": "The highest tag below this one, among tags matching ^v[0-9]+\\.[0-9]+\\.[0-9]+$, ordered by the three numbers.",
     "evidence": "For all 81 tags this equals `git describe --tags --abbrev=0 <tag>^`, which the current generator uses, and every earlier tag is an ancestor of every later one. The two definitions differ only if release lines diverge; the design text should name one."},
    {"id": "D2", "rule": "R1",
     "question": "Why the first-release form matters.",
     "decision": "`git rev-list <tag>`.",
     "evidence": "The current generator passes `..<tag>` to git-cliff; `..<tag>` means `HEAD..<tag>`, which is empty whenever HEAD is the tag or a descendant of it. Re-running git-cliff over `..<tag>` gives an empty list for all 10 first releases; over `<root>..<tag>` it lists 42 of the 61 pull requests those releases omitted (the other 19 are dropped by the filters)."},
    {"id": "D3", "rule": "R2",
     "question": "What is 'anywhere in the repository's history'?",
     "decision": "Every commit reachable from any ref of the clone (`git log --all`: remote-tracking branches and tags).",
     "evidence": "A CI checkout must therefore fetch all branches and tags (actions/checkout with fetch-depth: 0). A GitHub-made commit that lives only on a deleted branch is invisible: smalt-mcp #41 was merged into the since-deleted claude branch and its merge commit 9480437 is in no fetched ref. No listing in the measured history depends on such a commit."},
    {"id": "D4", "rule": "R2(a)",
     "question": "Shape of a squash commit.",
     "decision": "Committer email noreply@github.com, exactly one parent, first line ending in '(#N)'; if the first line carries several, the last is taken.",
     "evidence": "GitHub is also the committer of commits that are not pull-request merges: the root commits GitHub made when five repositories were created ('Initial commit', 'Add woot.md with initial content') and Dependabot's branch commits (deco-assaying f36d25c, baa63f5). None ends in '(#N)', so none is attributed; the root commits are direct commits."},
    {"id": "D5", "rule": "R2(b)",
     "question": "Which commits are a real merge's own commits, and what if another pull request's commit is among them?",
     "decision": "`git rev-list P2 [P3 ...] ^P1`, intersected with the range. A GitHub-made commit of another, non-carrier pull request among them is still that pull request (listed on its own); everything else among them (branch commits, local merges, carrier merges) belongs to the enclosing pull request and is never listed on its own.",
     "evidence": "64 commits are absorbed this way across the ten repositories. The only nested case in the data is smalt-mcp #38, which contains carrier #37's merge 8f0fb81; it is absorbed. No non-carrier pull request is nested inside another, so the first half of the decision is exercised only by construction."},
    {"id": "D6", "rule": "R2(c)",
     "question": "How patch-ids are computed, and in what order the two tests run.",
     "decision": "Non-merge commit: `git patch-id --stable` over `git log -p --no-renames`. GitHub-made merge: over `git diff --no-renames M^1 M`, which is what `git cherry-pick -m 1 M` applies. The '(cherry picked from commit X)' trailer is tested first, then the patch-id. A merge is never taken to be a cherry-pick. If several pull requests share a patch-id, the lowest number is taken.",
     "evidence": "The two conception-space picks (ad6975c, 1681b10) carry no trailer and are recognised by patch-id. `git cherry-pick -m 1` of a real merge is recognised in the supplementary synthetic scenario. No patch-id is shared by two pull requests in the data."},
    {"id": "D7", "rule": "R2(c)",
     "question": "Can a commit be a cherry-pick of a carrier pull request?",
     "decision": "Carrier pull requests are left out of the patch-id index, so no commit is taken to be a cherry-pick of one.",
     "evidence": "In 12 carrier merges the first-parent diff equals the diff of a single commit, because the carrier brought exactly one change (for example cogrind-workshop #1 and 958c3f5, smalt-mcp #36 and #37 and the 'release v1.2.0' commits). Without the exclusion those commits would be attributed to the carrier and vanish from the list; in the data that would drop cogrind-workshop 958c3f5."},
    {"id": "D8", "rule": "R2(c)",
     "question": "A real-merge pull request picked commit by commit.",
     "decision": "Not recognised by the rule as written; the picks are direct commits and the pull request is listed again when its merge reaches a release.",
     "evidence": "Supplementary synthetic scenario, #3: v1.0.0 lists 'exporter: module' and 'exporter: wiring' under Direct commits and v1.1.0 lists #3. The measured history contains no such pick. Either prescribe `git cherry-pick -m 1 <merge>` for hotfixes, or extend R2(c) so that a pull request whose own commits' patch-ids all occur in an earlier release counts as shipped there."},
    {"id": "D9", "rule": "R3",
     "question": "Is every pull request whose base branch is main a carrier?",
     "decision": "Implemented as written; the clause misclassifies one pull request.",
     "evidence": "cogrind-workshop #1 (ci-node24-action-pins into main) is a real change; R3 leaves it out and its one commit, 958c3f5 'ci: bump action pins to Node 24', appears under Direct commits. The other 21 carriers all have head develop or main. With the base-main clause removed, cogrind-workshop v0.1.0 lists #1 under Maintenance (checked). No pull request in the data has a head branch beginning 'back-merge'; that clause serves the proposed flow only."},
    {"id": "D10", "rule": "R3",
     "question": "What does 'as if it were not there' do to the carrier's own merge commit?",
     "decision": "A carrier merged for real is treated as a merge that is not a pull-request merge: its merge commit is tested under R5(iii), and its own commits are not absorbed but examined one by one. A carrier merged by squash cannot be handled (the changes it carries are not in the range as separate commits); the script leaves it out with a warning.",
     "evidence": "21 carrier merge commits tested, all equal to the automatic merge of their parents; the 22nd, smalt-mcp #37, lies inside #38 and is absorbed. All 22 carriers are real merges, so the squash case does not occur."},
    {"id": "D11", "rule": "R4",
     "question": "What is 'reachable from the previous tag', and is only the previous tag consulted?",
     "decision": "Attribution under R2 (a, b, c) over every commit of `git rev-list <prev>`, the whole ancestry of the previous tag; only the version-previous tag is consulted.",
     "evidence": "With diverging release lines a pull request shipped on another line could be listed again; 'reachable from any earlier tag' would avoid that. In the measured history every earlier tag is an ancestor of every later one, so the two readings agree. R4 acts twice: conception-space v0.8.3 does not list #11 and #12, shipped by cherry-pick in v0.8.2."},
    {"id": "D12", "rule": "R5(i)",
     "question": "When does a diff 'change only the version value'?",
     "decision": "Version files are recognised at the repository root only. A file passes if every line the diff changes matches ^\\s*\"?version\"?\\s*[:=] and the parsed file, with the project's own version removed, is identical before and after. The project's own lockfile entry is the uv.lock [[package]] whose source is editable or virtual '.', or whose name equals [project].name (names normalised); the Cargo.lock [[package]] named as [package].name; the top-level and packages[\"\"] version in package-lock.json. A version file that is added or deleted fails. Lockfile-only version changes pass.",
     "evidence": "112 commits recognised ('release vX' 67, open-cycle 36, 'chore: dev build' 4, jonobones 'version X' 3, one 'ops: bump version', one 'Revert \"release v1.2.0\"'). conception-space's bumps, which touch package.json and package-lock.json, are recognised. The synthetic dependency pin (pyproject.toml dependency and uv.lock specifier) is listed under Direct commits. Neither failure mode of F46 occurs."},
    {"id": "D13", "rule": "R5(ii)",
     "question": "Which CHANGELOG.md, and what about root commits?",
     "decision": "The root-level CHANGELOG.md, added, modified or deleted. A root commit is compared with the empty tree, so it is bookkeeping only if it adds nothing but CHANGELOG.md.",
     "evidence": "40 commits, all 'docs(changelog): vX [skip ci]'. The first commit of each of the ten repositories adds project files and is listed under Direct commits (10 of the 72)."},
    {"id": "D14", "rule": "R5",
     "question": "An empty commit (no diff).",
     "decision": "Neither (i) nor (ii) applies, so it is listed under Direct commits, as the rule is written.",
     "evidence": "None occurs in the data. The design text should say whether an empty commit is bookkeeping."},
    {"id": "D15", "rule": "R5(iii)",
     "question": "How the automatic merge is computed and a difference reported.",
     "decision": "`git merge-tree --write-tree` of the first two parents. A conflicted automatic merge never equals the merge; a merge with more than two parents is not bookkeeping. The difference is reported as `git diff --stat <automatic tree> <merge tree>`.",
     "evidence": "109 merges examined in the ten repositories (88 that are not pull-request merges, 21 carrier merges): every tree equals the automatic merge, so no merge in the measured history carries changes of its own. The synthetic merge with an extra edit is listed under Direct commits with 'src/b.py | 2 +-'."},
    {"id": "D16", "rule": "R6",
     "question": "What counts as a recognised type?",
     "decision": "Header ^type(scope)?!?: followed by a blank, type letters only and matched case-insensitively. Anything else is Other changes, shown in full.",
     "evidence": "43 of the 202 listed pull requests fall under Other changes: titles such as 'C-1: ...', 'B-3: ...', 'tools: ...', 'search: ...', 'cleave: ...', 'Dockerfile: ...', 'schema+tools: ...'. GitHub's default revert title 'Revert \"...\"' has no type and would go under Other changes, not Reverts as cliff.toml's ^Revert rule put it; no revert pull request exists in the data."},
    {"id": "D17", "rule": "R6",
     "question": "Title at merge time or current title?",
     "decision": "As written: the first line of a squash or titled merge (the title at merge time), and the API title for a merge at GitHub's default title (the current title).",
     "evidence": "smalt-mcp #3, #6 and #11 were retitled 18 s, 22 min 16 s and 3 min 36 s after their default-title merges; their merge bodies keep the earlier titles, so the listed title follows later edits and cannot be regenerated from git. The merge body's first line equals the API title in 68 of 71 default-title merges; a squash's first line differs from the API title in 3 of 159 (ebony-enriching #17, flint-slating #6, conception-space #2). No group changes in the data. Taking the title at merge time from git in both cases would make R6 independent of the API."},
    {"id": "D18", "rule": "R7",
     "question": "Where is a BREAKING CHANGE line sought, and where is a breaking pull request listed?",
     "decision": "At the start of a line, case-sensitive, in the pull request's squash, merge or pick commit message, in every own commit of a real merge, and in the pull-request body. A breaking pull request is listed once, under Breaking changes. The major-version warning fires when the major number exceeds the previous tag's, never for a first release.",
     "evidence": "5 breaking pull requests, pensa-grex #65 to #69 in v3.0.0, all by '!'. Warnings for pensa-grex v2.0.0 and smalt-mcp v1.0.0; smalt-mcp's breaking change is stated only in prose in a commit body ('major bump; breaking change to ...'), which R7 does not read. The synthetic #3 is breaking through a footer in one of its branch commits."},
]

API_USE = {
    "github_api": [
        "R3: the base and head branch of each pull request.",
        "R6: the title of a pull request merged at GitHub's default title (see D17 for a git-only alternative).",
        "R7: the pull-request body.",
        "Optional cross-check: a GitHub-made commit ending in '(#N)' that is not the merge commit GitHub records for #N is reported (none in the data).",
    ],
    "git_alone": [
        "R1 ranges; R2 (a), (b) and (c) including patch-ids and trailers; R4; R5 (i), (ii) and (iii); R6 for squash, titled merges and cherry-picks; R7 for titles and commit messages.",
    ],
}

CORRECTIONS = [
    "Proposed rule against the truth: the earlier '80 of 81 exact' described the first prototype. The rule as designed lists exactly the expected pull requests (truth less carriers) in 79 of 81 releases; the other two, conception-space v0.8.2 (#11 and #12 listed as cherry-picks) and v0.8.3 (#11 and #12 not listed again), are correct behaviour. No release has an unexplained difference.",
    "Carriers: 22 merged pull requests, not 21. Besides the 21 release-promotion and back-merge pull requests, R3's 'base branch is main' clause catches cogrind-workshop #1, a feature pull request into main (D9).",
    "Truth: 224 merged pull requests have their merge commit in a release range; expected (less carriers) 202.",
    "Published omissions: 122 expected pull requests are not published by number, not 144; the difference is the 22 carriers. 5 of the 122 (deco-assaying #1, #3, #5, #8, #10) were published by commit hash.",
    "Causes, in the prescribed order: first release's empty range 61 (not 62: the 62nd was cogrind-workshop #1, now a carrier), tag published with no list 34, written prefix policy 26, default-title merge skipped by ^Merge 1, other 0.",
    "The 34 'no list' omissions all fall in tags whose list git-cliff empties with the repository's own configuration: 31 are default-title merges and 3 are ci or chore squashes. Counted by mechanism rather than in the prescribed order, the ^Merge skip drops 49 of the 122, the prefix policy 31, and the empty first-release range 61, of which 42 would have been listed with a correct range.",
    "Noise: 34 published list lines correspond to no pull request, not 39: 32 are the release job's own changelog commits and 2 are real changes made without a pull request (pensa-grex v3.1.0 d8f9d8e and baab775). The other 5 of the earlier 39 are deco-assaying pull-request commits cited by hash.",
    "Direct commits: 72 commits under the content rule, not 20 (mixed units) or 65 (second prototype, title regex). The 7 added are deco-assaying c260845 and f6d34ee, the root commits of jonobones, smalt-mcp, ebony-enriching and flint-slating (the regex skipped 'Initial commit'), and cogrind-workshop 958c3f5 (D9).",
    "Published artefacts: 50 of 81 tags have a GitHub Release; 26 fall back to a CHANGELOG.md section on main (23 of them with no list); 5 (jonobones v0.1.0 to v0.1.4) have neither and contain no pull request.",
]
